global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "vmagent"
    static_configs:
      - targets: ["vmagent:8429"]
  - job_name: "indexer"
    static_configs:
      - targets: ["indexer:3000"]
