-- AlterTable
ALTER TABLE "EtherFi" ALTER COLUMN "tvl" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "RocketPool" ALTER COLUMN "eth" SET DATA TYPE TEXT,
ALTER COLUMN "rpl" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "StakeWise" ALTER COLUMN "eth" SET DATA TYPE TEXT;
